schema = 3

[mod]
  [mod.'github.com/BurntSushi/toml']
    version = 'v1.3.2'
    hash = 'sha256-FIwyH67KryRWI9Bk4R8s1zFP0IgKR4L66wNQJYQZLeg='

  [mod.'github.com/amarbel-llc/purse-first/libs/go-mcp']
    version = 'v0.0.0-20260217222858-cd512e5ef8b7'
    hash = 'sha256-S7j8n/4sc6fDWFBnpbNJqfx4LgN+X0fT4eaTT2Ex2DY='

  [mod.'github.com/gobwas/glob']
    version = 'v0.2.3'
    hash = 'sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/spf13/cobra']
    version = 'v1.8.0'
    hash = 'sha256-oAE+fEaRfZPE541IPWE0GMeBBYgH2DMhtZNxzp7DFlY='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.5'
    hash = 'sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw='
