schema = 3

[mod]
  [mod.'github.com/BurntSushi/toml']
    version = 'v1.3.2'
    hash = 'sha256-FIwyH67KryRWI9Bk4R8s1zFP0IgKR4L66wNQJYQZLeg='

  [mod.'github.com/amarbel-llc/go-lib-mcp']
    version = 'v0.0.0-20260215160001-e634f96c4717'
    hash = 'sha256-DiqonnNwZdI7TaYKUlgmS3DsjOxWpVtiMmXVmwD5nwQ='

  [mod.'github.com/cpuguy83/go-md2man/v2']
    version = 'v2.0.3'
    hash = 'sha256-FAMxR5eBO9LQp6ev1b7zaPUS5aoNz1GtsPpoArjiJVw='

  [mod.'github.com/gobwas/glob']
    version = 'v0.2.3'
    hash = 'sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/russross/blackfriday/v2']
    version = 'v2.1.0'
    hash = 'sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ='

  [mod.'github.com/spf13/cobra']
    version = 'v1.8.0'
    hash = 'sha256-oAE+fEaRfZPE541IPWE0GMeBBYgH2DMhtZNxzp7DFlY='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.5'
    hash = 'sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
